### ISSUE TITLE
Sprites off center in WWF Wrestlemania

### ISSUE THREAD

**Issue by twinfami** [MiSTer-devel/S32X_MiSTer#13] opened 2022-04-22 14:21 UTC
![20220422_101933](https://user-images.githubusercontent.com/67311558/164733424-87cafe63-346b-4a61-8c8a-58dbe69dda9d.jpg)

All sprites are off center in WWF Wrestlemania as shown in the picture

**Comment by twinfami** [comment] 2022-04-22 14:22
![20220422_102159](https://user-images.githubusercontent.com/67311558/164733618-0dab08f7-e13c-4da5-95f0-4ffaaceaa6f4.jpg)

**Comment by Kitrinx** [comment] 2022-04-24 18:26
This is caused by attempting to use a 6 button controller with this game. Turn it to 3 buttons and it should work properly.

**Comment by JDash247** [comment] 2022-04-25 12:57
> This is caused by attempting to use a 6 button controller with this game. Turn it to 3 buttons and it should work properly.

This isn't a fix.  WWF does a reset during the first match regardless of 3 or 6 button.

**Comment by spotanime** [comment] 2022-04-25 13:47
Tested this on an Analogue Sg and 32X, with both original cart and rom via MegaSD. Both show 6-button options and sprites working correctly. 

ROM details:

Database match: WWF WrestleMania - The Arcade Game (USA)
Database: No-Intro: Genesis (v. 20210226-213851)
File/ROM SHA-1: 551EEDC963CBA0E1410B3D229B332EF9EA061469
File/ROM CRC32: 61833503

![wwfrom](https://user-images.githubusercontent.com/76781697/165102098-f79ac66e-5a44-44e8-a40a-01aec67b5871.png)

**Comment by Kitrinx** [comment] 2022-04-25 13:48
Yes, it is a bug. But you can evade it for now until it's figured out.

**Comment by thehughhefner** [comment] 2022-06-08 12:11
With the latest release, can you test?

**Comment by JDash247** [comment] 2022-06-08 18:53
Just tested this and the 6-button problem is gone and it doesn't reset

**Comment by a-barone** [comment] 2022-06-14 13:26
I can confirm that this issue has been fixed by the S32X_20220607.rbf core. I can't reproduce it anymore.
This issue can be closed.

**Closed** 2022-06-14 21:16 UTC
