### ISSUE TITLE
Knuckles Chaotix crashes after special stage

### ISSUE THREAD

**Issue by dpowers86** [MiSTer-devel/S32X_MiSTer#3] opened 2022-04-20 22:11 UTC
I played for about 20 min and made it to the [special stage](https://sonic.fandom.com/wiki/Special_Stage_(Knuckles%27_Chaotix)). I completed it successfully but as soon as it ended, the screen remained black with music playing. Controls aren't having any effects except I can get in and out of the MiSTer menu.

Core had to be reloaded to fix. Reset did not work.

ROM Checksum: `47b1095e68b053125cd2cd5b1ac4eb50  Chaotix ~ Knuckles' Chaotix (Japan, USA).32x`

Settings I changed from defaults
Region: US
ROM Storage: SDRAM
Sprite Limit: High

Composite Blend: Adaptive
Audio Filter: No Filter
HiFi PCM: Yes

Thanks for all the effort on the core! This was a delightful surprise today.

**Comment by fingusk** [comment] 2022-05-05 14:23
I have the exact same issue. once bonus level is complete, screen goes black, music is on but cant get any further. Awesome core tho. hope for a fix soon

**Comment by thehughhefner** [comment] 2022-06-07 10:16
According to users on the official mister discord, this issue seems to be fixed with the latest commits

**Comment by thehughhefner** [comment] 2022-06-08 12:10
Is this fixed?

**Comment by fingusk** [comment] 2022-06-08 12:44
Hi. Seems to be fine but saves not working for some reason!!

**Comment by Yamato-san** [comment] 2022-06-14 10:21
I can confirm that the game does not crash anymore after completing the special stage. I was able to select a different character and continue playing the next stage. Thank you!

**Comment by thehughhefner** [comment] 2022-06-14 10:23
Then this ticket can be closed

**Comment by fingusk** [comment] 2022-06-14 11:11
Yeah. It can be closed now. Thanks for sorting it out. Looking forward to sram backup being implemented now

**Closed** 2022-06-14 21:16 UTC
